apiVersion: v1
kind: Secret
metadata:
  name: lop-local-dev-secret
  namespace: dev
type: Opaque
stringData:
  DB_HOST: postgres.database.svc
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD: strongpassword123
  DATABASE_URL: postgresql+psycopg://appuser:strongpassword123@postgres.database.svc:5432/appdb
  SECRET_KEY: lop-local-dev-secret-key-not-for-production
  CORS_ORIGINS: '["http://lop.localhost:8080"]'
  NEXT_PUBLIC_API_BASE_URL: http://lop.localhost:8080/api/v1
  GITHUB_API_TOKEN: ""
